version: '3.9'
services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jhwu
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - iot_network      
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jhwu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://jhwu:secret@db:27017/
    depends_on:
      - db
    networks:
      - iot_network      
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - iot_network

networks:
  iot_network:

